---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: system/serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pixiu-pixiu-io-v1alpha1-podset
  failurePolicy: Fail
  name: mpodset.kb.io
  rules:
  - apiGroups:
    - pixiu.pixiu.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podsets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: system/serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pixiu-pixiu-io-v1alpha1-podset
  failurePolicy: Fail
  name: vpodset.kb.io
  rules:
  - apiGroups:
    - pixiu.pixiu.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podsets
  sideEffects: None
