# permissions for end users to view podsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podset-viewer-role
rules:
- apiGroups:
  - pixiu.pixiu.io
  resources:
  - podsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pixiu.pixiu.io
  resources:
  - podsets/status
  verbs:
  - get
